server:
  error:
    include-stacktrace: never

# expose actuator for SBA
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  zipkin:
    baseUrl:  ${ZIPKIN_URL:http://localhost:9411}
  jmx:
    enabled: false

---

spring:
  profiles: dev
  sleuth.sampler.probability: 1.0

server:
  error:
    include-stacktrace: always

#Setting logging levels
logging:
  level:
    com.netflix: DEBUG
    org.springframework.web: DEBUG
    org.springframework.http: TRACE
    com.tictactoecorp: DEBUG
