spring:
  sleuth.sampler.probability: 1.0
  zipkin:
    baseUrl:  ${ZIPKIN_URL:http://localhost:9411}
  jmx:
    enabled: false

# expose actuator for SBA
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS
