server.port: ${WEBAPI_PORT:40001}

spring:
  profiles:
    include: microservice
    active: ${ARTICLE_ACTIVE_PROFILE:default}
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      database: ${MONGO_DATABASE:shashki}
      port: ${MONGO_PORT:27017}
