server.port: ${WEBAPI_PORT:40002}

spring:
  profiles:
    include: microservice
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      database: ${MONGO_DATABASE:shashki}
      port: ${MONGO_PORT:27017}
