server:
  port: ${GATEWAY_SERVER_PORT:5555}

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:4000"
              - "https://www.shashki.online"
              - "https://shashki.online"
            allowedHeaders:
              - Content-Type
              - Authorization
            allowedMethods:
              - GET
              - POST
              - PUT
      routes:
        - id: editservice-shashki
          uri: lb://editservice-shashki
          predicates:
            - Path=/edit/**
          filters:
            - StripPrefix=1
        - id: articleservice-shashki
          uri: lb://articleservice-shashki
          predicates:
            - Path=/article/**
          filters:
            - StripPrefix=1
        - id: boardservice-shashki
          uri: lb://boardservice-shashki
          predicates:
            - Path=/board/**
          filters:
            - StripPrefix=1

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 21000
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000

eureka:
  instance:
    # to allow SBA access this service
    metadata-map:
      user.name: "actuator"
      user.password: "{cipher}0be8db7b852008bd5671b89761885647d2ea94a70bac81b8bbfd1fb7787793af6b100c16693e202d1a55b06b0584bdf4"

# expose actuator for SBA
management:
  endpoints:
    web.exposure.include: health,refresh
  endpoint:
    health:
      show-details: never
